docs_dir: docs/book
site_dir: docs/html
nav:
    - Home: index.md
    - v1:
      - Introduction: v1/intro.md
site_name: 'laminas-servicemanager-inspector'
site_description: 'Container inspection and verification tools for laminas-servicemanager.'
repo_url: 'https://github.com/laminas/laminas-servicemanager-inspector'
extra:
    project: Components
    current_version: v1
    versions:
      - v1
